//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityfm_db_firts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public short Id { get; set; }
        public entityfm_db_first.Levelb Level1 { get; set; }
    }
}
